server.port=8081
spring.application.name=cliente-service-alunos
spring.cloud.config.uri=http://localhost:8888
application-version=v1

# Configuração local do MongoDB (caso o Config Server não esteja rodando)
spring.data.mongodb.uri=mongodb://localhost:27017/vendas_online
